services:

  app:
    container_name: main_app
    build: .
    command:
      bash -c "cd ./blog ;
      python -m uv run python manage.py migrate ;
      sleep 5 ;
      python -m uv run python manage.py prepare ;
      python -m uv run python manage.py runserver 0.0.0.0:8000"
    env_file:
      - dev.env
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: db_app
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - dev.env
    expose:
      - 5432
    ports:
      - "5432:5432"